/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zacxophone (https://sketchfab.com/Zacxophone)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/birds-3a9bb97be78944f9bffc23fb25c2154e
Title: Birds
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import birds from "../assets/3d/birds.glb";
import { useFrame } from "@react-three/fiber";

const Birds = () => {
  const group = useRef();
  const { scene, animations } = useGLTF(birds);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Scene"].play();
  }, []);

  useFrame(({ clock, camera }) => {
    // Update Y position with a sinusoidal motion
    group.current.position.y = Math.sin(clock.elapsedTime) * 0.2 + 2;

    // Update X position for left-to-right movement
    if (group.current.rotation.y === 0) {
      group.current.position.x += 0.01; // Move right
    } else {
      group.current.position.x -= 0.01; // Move left
    }

    // If the birds move out of the camera's view on the right, reset their position
    if (group.current.position.x > camera.position.x + 10) {
      group.current.position.x = camera.position.x - 10;
    }
  });

  return (
    <mesh
      position={[0, 2, -30]}
      rotation={[0, Math.PI / 2, 0]}
      scale={[1, 1, 1]}
      ref={group}
    >
      <primitive object={scene} />
    </mesh>
  );
};

export default Birds;
